# Enable validation, metrics, and logging in production
spring:
  application:
    name: url-analyzer
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    root: INFO
    com.urlanalyzer: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics